### ISSUE TITLE
rendererFn报错

### ISSUE THREAD

**Issue by jiasswee** [TimeRainStarSky/Yunzai-ICQQ-Plugin#3]
node app
[TRSSYz][15:39:58.409][MARK] ----^_^----
[TRSSYz][15:39:58.415][MARK] TRSS-Yunzai v3.1.0 启动中...
[TRSSYz][15:39:58.415][MARK] https://github.com/TimeRainStarSky/Yunzai
[TRSSYz][15:39:58.494][MARK] 正在连接 Redis...
[TRSSYz][15:39:58.494][MARK] redis://127.0.0.1:6379/0
[TRSSYz][15:39:59.696][MARK] Redis 连接成功
SyntaxError: Unexpected token '??='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:149:18)
file:///root/Yunzai/lib/renderer/Renderer.js:23
    let renderer = rendererFn(rendererCfg)
                   ^

TypeError: rendererFn is not a function
    at registerRendererBackends (file:///root/Yunzai/lib/renderer/Renderer.js:23:20)
    at async file:///root/Yunzai/lib/renderer/Renderer.js:32:1

**Comment by TimeRainStarSky** [comment]
```sh
git reset --hard
git pull
```
